config/routes.rb
Rails.application.routes.draw do
  root 'manufacturers#index'

  resources :manufacturers, only: [:new, :create, :index]

  resources :cars, only: [:new, :create, :index]

end

app/models/car.rb
class Car < ActiveRecord::Base

  belongs_to :manufacturer

  start_year_range = Time.now.year - 95
  end_year_range = Time.now.year

  year_range = (start_year_range..end_year_range).map{|year| "31-12-#{year}".to_date}

  validates :year, presence: true, inclusion: {:in => year_range}

  validates :color, presence: true, inclusion: {within: ['Black', 'Blue', 'Silver', 'Gold',
    'Green','Dark Gray','Gray','Red','Yellow', 'White','Rust','Orange','Lime Green','Beige',
    'Brown','Metallic Gray'], message: "Must be real car color"}
  validates :model, presence: true,
  length: {
  minimum: 4,
  maximum: 25
  }
  validates :mileage, presence: true, numericality: true
  validates :description, length: { maximum: 500 }
  validates_uniqueness_of :model, scope: [:color, :mileage, :year]
end

app/models/manufacturer.rb
class Manufacturer < ActiveRecord::Base
  has_many :cars

  validates :name, presence: true, uniqueness: true,
  length: {
  minimum: 2,
  maximum: 25
  }
  validates :country, presence: true
  validates :description, length: { maximum: 500 }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/cars_controller.rb
class CarsController < ApplicationController

  def index
    @cars = Car.all
  end

  def new
    @car = Car.new
    @manufacturers = Manufacturer.all
  end


  def create

    @manufacturer = Manufacturer.find(params[:car][:id])
    params[:car][:year] = "31-12-#{params[:car][:year]}".to_date
    params[:car][:color] = params[:car][:color].capitalize
    @car = @manufacturer.cars.build(car_params)

    if @car.save
      redirect_to cars_path, :notice => "Car successfully added"
    else
      @manufacturers = Manufacturer.all
      render :new
    end
  end

  protected

  def car_params
    params.require(:car).permit(:model, :color, :manufacturer_id,:mileage, :year)
  end

end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def index
  end
end

app/controllers/manufacturers_controller.rb
class ManufacturersController < ApplicationController
  def index
    @manufacturers = Manufacturer.all
  end
  def new
    @countries = Country.all
    @manufacturer = Manufacturer.new
  end

  def create

    params[:manufacturer][:country] = params[:country]

    @manufacturer = Manufacturer.create(manufacturer_params)

    if @manufacturer.save
      redirect_to manufacturers_path, :notice => "Manufacturer successfully added"
    else
      @countries = Country.all
      render :new
    end
  end

  protected

  def manufacturer_params
    params.require(:manufacturer).permit(:name, :description, :country)
  end

end

app/views/cars/index.html.erb
<div class="row">
  <div class="large-6 large-offset-3 columns">

  <li><%= link_to "Add new Car", new_car_path%></li>
  <li><%= link_to "Add new manufacturer", new_manufacturer_path%></li>
  <li><%= link_to "Home", manufacturers_path%></li>

  <h1>Car Details</h1>

  <ul>
    <% @cars.each do |car| %>
      <li>Model : <%= car.model %></li>
      <li>Color : <%= car.color %></li>
      <li>Mileage : <%= car.mileage.round(0) %></li>
      <li>Year : <%= car.year.year %></li>
      <li>Manufacturer : <%= car.manufacturer.name %></li>
      <br>
    <% end %><br>
  </ul>

  </div>
</div>

app/views/cars/new.html.erb
<div class="row">
  <div class="large-8 large-offset-2 columns">

  <li><%= link_to "Add new Manufacturer", new_manufacturer_path %></li>
  <li><%= link_to "View all Cars", cars_path%></li>
  <li><%= link_to "Home", manufacturers_path %></li>

  <%= form_for(@car) do |f| %>
    <h1> Enter new Car information </h1>
    <% if @car.errors.any? %>
      <div id="error_explanation">
        <h2><%= "#{@car.errors.count} errors prevented the car from being saved" %></h2>
        <ul>
        <% @car.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
        </ul>
      </div>
    <% end %>

    <div class="field">
    <h3> Choose manufacturer </h3>
    <%= f.collection_select :id, @manufacturers, :id, :name %>
    </div>

    <div class="field">
      <%= f.label :model %><br>
      <%= f.text_field :model %>
    </div>
    <div class="field">
    <%= f.label :year %><br>
    <%= f.select :year, (Time.zone.now.year - 95)..(Time.zone.now.year + 1)%>
    </div>

    <div class="field">
        <%= f.label :color %><br />
        <%= f.text_field :color %>
      </div>

    <div class="field">
      <%= f.label :mileage %><br />
      <%= f.text_field :mileage %>
    </div>

    <div class="field">
      <%= f.label :description %><br />
      <%= f.text_field :description %>
    </div>

    <div class="actions">
    <%= f.submit "Submit" %>
    </div>

    <%end%>
  </div>
</div>

app/views/homes/index.html.erb
<p>
  Modify me in `app/views/homes/index.html.erb` or change the root directive in
  `config/routes.rb`
</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>CarListings</title>
  <%= stylesheet_link_tag 'application', media: 'all' %>
  <%= csrf_meta_tags %>
</head>
<body>
  
  <nav class="top-bar">
    <ul class="title-area">
      <li class="name">
        <h1><a href="/">CarListings</a></h1>
      </li>
    </ul>

    <section class="top-bar-section">
      <ul class="right">
       
      </ul>
    </section>
  </nav>

  <%- flash.each do |key, value| -%>
    <div class="flash flash-<%= key %>">
      <%= value %>
    </div>
  <%- end -%>

  <%= yield %>

  <%= javascript_include_tag 'application' %>
  <%= javascript_tag do %>
    $(function(){
      $(document).foundation();
    });
  <% end %>
  <%= yield :extra_footer %>
</body>
</html>

app/views/manufacturers/index.html.erb
<div class="row">
  <div class="large-6 large-offset-3 columns">
    <li><%= link_to "Add new Manufacturer", new_manufacturer_path %></li>
    <li><%= link_to "Add new Car", new_car_path %></li>
    <li><%= link_to "View all Cars", cars_path%></li>
    <h1>Manufacturers</h1>

    <ul>
      <% @manufacturers.each do |manufacturer| %>
        <li><%= manufacturer.name%> - <%=manufacturer.country%></li>
        <li>-------------</li>
        <p><%manufacturer.cars.each do|car|%>
        <li>Model : <%=car.model%></li>
        <%end%></p><br>
     <% end %>
    </ul>

  </div>
</div>

app/views/manufacturers/new.html.erb
<div class="row">
  <div class="large-8 large-offset-2 columns">
    <li><%= link_to "Home", manufacturers_path%></li>
    <li><%= link_to "Add new Car", new_car_path %></li>
    <li><%= link_to "View all Cars", cars_path%></li>
    <%= form_for(@manufacturer) do |f| %>

    <% if @manufacturer.errors.any? %>
      <div id="error_explanation">
        <h2><%= "#{@manufacturer.errors.count} errors prevented the manufacturer from being saved" %></h2>
        <ul>
          <% @manufacturer.errors.full_messages.each do |message| %>
            <li><%= message %></li>
          <% end %>
        </ul>
      </div>
    <% end %>


      <h1>Add new manufacturer</h1>
      <div class="field">
        <%= f.label :name %><br />
        <%= f.text_field :name %>
      </div>

      <div class="field">
        <h3> Choose country </h3>
        <%=select_tag "country", options_for_select(@countries, selected: ['United States', 'US'])%>
        </div>

      <div class="field">
        <%= f.label :description %><br />
        <%= f.text_field :description %>
      </div>
      <div class="actions">
      <%= f.submit "Submit" %>
      </div><br>

    <% end %>


  </div>
</div>